name: Test and Build

on: [push, pull_request]

permissions:
  pull-requests: write
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run test with coverage
        run: npm run coverage
      - name: Codecov
        uses: codecov/codecov-action@v4

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build project
        run: npm run build
        env:
          CI: true
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

  dependabot-automerge:
    if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
    needs: 
      - lint
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
