name: Test

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run test
        run: npm run test
